version: "3.8"

services:
  api:
    build: ./todo-api
    ports:
      - 3001:3001

  ui:
    build: ./todo-ui
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3001/api
